# Generated by Django 2.2.2 on 2019-07-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190730_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=30, verbose_name="person's first name"),
        ),
    ]
