# Generated by Django 2.2.2 on 2019-07-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190730_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(default=True, max_length=120),
            preserve_default=False,
        ),
    ]
