# Generated by Django 2.2.2 on 2019-07-31 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190730_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=models.TextField(verbose_name='Make a post here!'),
        ),
    ]
